"""MockSatelliteProvider -- DEMO_MODE fallback. Serves scenes from the
synthetic demo dataset under data/demo/, described honestly by
data/demo/metadata/manifest.json (generated by scripts/generate_demo_data.py).

This never pretends to be a real satellite provider: every SceneCandidate
it returns has demo_mode=True and sensor="synthetic_demo".
"""
from __future__ import annotations

import json
from datetime import date, datetime, timezone
from pathlib import Path

from app.schemas.location import LocationRequest
from app.schemas.satellite import DownloadResult, ProviderStatus, SceneCandidate
from app.satellite.providers.base import SatelliteDataProvider

_REPO_ROOT = Path(__file__).resolve().parents[4]
_MANIFEST_PATH = _REPO_ROOT / "data" / "demo" / "metadata" / "manifest.json"


class MockSatelliteProvider(SatelliteDataProvider):
    provider_id = "mock_demo"

    def check_availability(self) -> ProviderStatus:
        if not _MANIFEST_PATH.exists():
            return ProviderStatus(
                provider=self.provider_id,
                status="unavailable_error",
                message="Demo dataset manifest not found. Run scripts/generate_demo_data.py.",
            )
        return ProviderStatus(provider=self.provider_id, status="healthy")

    def _load_manifest(self) -> list[dict]:
        if not _MANIFEST_PATH.exists():
            return []
        with open(_MANIFEST_PATH, encoding="utf-8") as f:
            return json.load(f).get("scenes", [])

    def search_scenes(
        self, aoi: LocationRequest, date_range: tuple[date, date], modality: str
    ) -> list[SceneCandidate]:
        entries = [e for e in self._load_manifest() if e.get("modality") == modality]
        candidates = []
        for entry in entries:
            candidates.append(
                SceneCandidate(
                    provider=self.provider_id,
                    scene_id=entry["scene_id"],
                    product_id=entry.get("product_id"),
                    acquisition_time=datetime.fromisoformat(entry["acquisition_time"]).replace(
                        tzinfo=timezone.utc
                    ),
                    cloud_percentage=entry.get("cloud_percentage"),
                    bbox=tuple(entry["bbox"]) if entry.get("bbox") else None,
                    crs=entry.get("crs"),
                    resolution=entry.get("resolution"),
                    modality=modality,
                    sensor="synthetic_demo",
                    demo_mode=True,
                )
            )
        return candidates

    def get_metadata(self, scene_id: str) -> SceneCandidate | None:
        for entry in self._load_manifest():
            if entry["scene_id"] == scene_id:
                return SceneCandidate(
                    provider=self.provider_id,
                    scene_id=scene_id,
                    modality=entry.get("modality", "optical"),
                    sensor="synthetic_demo",
                    demo_mode=True,
                    crs=entry.get("crs"),
                )
        return None

    def download_scene(self, scene_id: str, destination_dir: str) -> DownloadResult:
        for entry in self._load_manifest():
            if entry["scene_id"] == scene_id:
                source_path = _REPO_ROOT / entry["file_path"]
                if not source_path.exists():
                    return DownloadResult(success=False, error="Demo scene file missing on disk.")
                return DownloadResult(success=True, local_path=str(source_path))
        return DownloadResult(success=False, error=f"Unknown demo scene_id '{scene_id}'.")
