"""initial schema

Revision ID: ee4074e6ef1b
Revises: 
Create Date: 2026-09-05 20:27:41.467023

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee4074e6ef1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('capability', sa.JSON(), nullable=False),
    sa.Column('modalities', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=300), nullable=True),
    sa.Column('fallback_model_id', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_model_id'), 'model_registry', ['model_id'], unique=True)
    op.create_table('satellite_scenes',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('scene_id', sa.String(length=200), nullable=False),
    sa.Column('product_id', sa.String(length=200), nullable=True),
    sa.Column('acquisition_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cloud_percentage', sa.Float(), nullable=True),
    sa.Column('bbox_geojson', sa.JSON(), nullable=True),
    sa.Column('crs', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.Float(), nullable=True),
    sa.Column('modality', sa.String(length=30), nullable=False),
    sa.Column('download_status', sa.String(length=30), nullable=False),
    sa.Column('local_image_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_scenes_acquisition_time'), 'satellite_scenes', ['acquisition_time'], unique=False)
    op.create_index(op.f('ix_satellite_scenes_provider'), 'satellite_scenes', ['provider'], unique=False)
    op.create_index(op.f('ix_satellite_scenes_scene_id'), 'satellite_scenes', ['scene_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('model_versions',
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('trained_on', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.model_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_model_id'), 'model_versions', ['model_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('dataset', sa.String(length=100), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('modality', sa.String(length=30), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_session_id'), 'images', ['session_id'], unique=False)
    op.create_table('messages',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('image_metadata',
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('crs', sa.String(length=50), nullable=True),
    sa.Column('bounds_geojson', sa.JSON(), nullable=True),
    sa.Column('resolution_x', sa.Float(), nullable=True),
    sa.Column('resolution_y', sa.Float(), nullable=True),
    sa.Column('band_count', sa.Integer(), nullable=True),
    sa.Column('band_descriptions', sa.JSON(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('sensor', sa.String(length=100), nullable=True),
    sa.Column('spatial_reference_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_metadata_image_id'), 'image_metadata', ['image_id'], unique=True)
    op.create_table('queries',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('detected_language', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_session_id'), 'queries', ['session_id'], unique=False)
    op.create_table('task_plans',
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('modalities', sa.JSON(), nullable=False),
    sa.Column('temporal', sa.Boolean(), nullable=False),
    sa.Column('requires_two_images', sa.Boolean(), nullable=False),
    sa.Column('requires_grounding', sa.Boolean(), nullable=False),
    sa.Column('requires_quantification', sa.Boolean(), nullable=False),
    sa.Column('location_json', sa.JSON(), nullable=True),
    sa.Column('date_range_json', sa.JSON(), nullable=True),
    sa.Column('output_type', sa.JSON(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_plans_query_id'), 'task_plans', ['query_id'], unique=False)
    op.create_table('executions',
    sa.Column('task_plan_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('data_provenance_json', sa.JSON(), nullable=True),
    sa.Column('model_provenance_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_plan_id'], ['task_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_status'), 'executions', ['status'], unique=False)
    op.create_index(op.f('ix_executions_task_plan_id'), 'executions', ['task_plan_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('execution_id', sa.String(), nullable=True),
    sa.Column('event_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_execution_id'), 'audit_logs', ['execution_id'], unique=False)
    op.create_table('evidence',
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('coordinates_json', sa.JSON(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('area_percentage', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_execution_id'), 'evidence', ['execution_id'], unique=False)
    op.create_table('execution_steps',
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('step_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_steps_execution_id'), 'execution_steps', ['execution_id'], unique=False)
    op.create_table('reports',
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_execution_id'), 'reports', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_execution_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_execution_steps_execution_id'), table_name='execution_steps')
    op.drop_table('execution_steps')
    op.drop_index(op.f('ix_evidence_execution_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_audit_logs_execution_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_executions_task_plan_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_status'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_task_plans_query_id'), table_name='task_plans')
    op.drop_table('task_plans')
    op.drop_index(op.f('ix_queries_session_id'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_image_metadata_image_id'), table_name='image_metadata')
    op.drop_table('image_metadata')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_images_session_id'), table_name='images')
    op.drop_table('images')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_model_versions_model_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_satellite_scenes_scene_id'), table_name='satellite_scenes')
    op.drop_index(op.f('ix_satellite_scenes_provider'), table_name='satellite_scenes')
    op.drop_index(op.f('ix_satellite_scenes_acquisition_time'), table_name='satellite_scenes')
    op.drop_table('satellite_scenes')
    op.drop_index(op.f('ix_model_registry_model_id'), table_name='model_registry')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
