import type { ExecutionResult, SessionDetail, SessionSummary } from "./types";

export interface MockSessionItem extends SessionSummary {
  updated_at: string;
  category: "Today" | "Yesterday" | "Previous 7 Days" | "Older";
  detail: SessionDetail;
  result: ExecutionResult;
}

export const MOCK_SESSIONS: MockSessionItem[] = [
  {
    id: "session-pune-growth",
    title: "Pune Urban Growth",
    language: "en",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    category: "Today",
    detail: {
      id: "session-pune-growth",
      title: "Pune Urban Growth",
      language: "en",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      messages: [
        {
          id: "m-1",
          execution_id: null,
          role: "user",
          content: "What changed between these two Sentinel-2 images of Pune peri-urban region?",
          created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        },
        {
          id: "m-2",
          execution_id: "exec-pune-001",
          role: "assistant",
          content:
            "Built-up development increased significantly across the northern portion of the area of interest (+12.4 hectares). Agricultural parcels transitioned into construction staging and compacted impervious surfaces between January 2024 and December 2024.",
          created_at: new Date(Date.now() - 1000 * 60 * 58 * 2).toISOString(),
        },
      ],
    },
    result: {
      execution_id: "exec-pune-001",
      status: "completed",
      task: "change_vqa",
      model: "SatQuery Change (ChangeFormer)",
      model_version: "2.1.0-georef",
      answer:
        "Built-up development increased across the northern portion of the area of interest (+12.4 hectares). Spectral change masks indicate conversion from low-biomass fallow plots to high-reflectance commercial and transport infrastructure.",
      evidence: [
        {
          type: "before_after",
          storage_key: "demo/temporal/comparison_composite.png",
          coordinates: [73.8567, 18.5204, 73.9142, 18.5789],
          geo_geometry: {
            type: "Polygon",
            coordinates: [
              [
                [73.8567, 18.5204],
                [73.9142, 18.5204],
                [73.9142, 18.5789],
                [73.8567, 18.5789],
                [73.8567, 18.5204],
              ],
            ],
          },
          label: "Bi-Temporal Alignment (T1: 2024-01-12 | T2: 2024-12-18)",
          score: 0.94,
          area_m2: 124000,
          area_percentage: 14.2,
        },
        {
          type: "change_mask",
          storage_key: "demo/temporal/change_mask_overlay.png",
          coordinates: [73.871, 18.542, 73.902, 18.571],
          geo_geometry: null,
          label: "Built-up Expansion (Otsu + Morphological Filtering)",
          score: 0.91,
          area_m2: 124000,
          area_percentage: 14.2,
        },
      ],
      confidence: {
        mode: "calibrated",
        overall_level: "high",
        model_confidence: 0.89,
        input_quality: "good",
        evidence_quality: "strong",
        modality_agreement: "agree",
        notes: [
          "Co-registration RMSE < 0.32 pixels",
          "Zero cloud contamination in validated AOI",
          "Calculated using EPSG:32643 UTM Zone 43N projected coordinates",
        ],
      },
      data_provenance: {
        provider: "Copernicus Sentinel-2 L2A",
        scene_id: "S2B_MSIL2A_20241218T053219_R019",
        acquisition_date: "2024-12-18T05:32:19Z",
        sensor: "MSI Optical",
        aoi: { type: "BBox", bounds: [73.8567, 18.5204, 73.9142, 18.5789] },
        crs: "EPSG:32643",
        resolution: 10,
        processing_applied: ["Orthorectification", "Atmospheric Correction", "Bilinear Warp Co-registration"],
        retrieved_at: "2026-03-01T10:00:00Z",
      },
      model_provenance: {
        model_id: "satquery-change-former",
        version: "2.1.0",
        capability: "change_detection",
        configuration: { threshold: "otsu_adaptive", window_size: 512 },
        fallback_used: false,
        fallback_reason: null,
        demo_mode: false,
      },
      warnings: [],
      user_message: null,
      actions: ["Export GeoJSON", "Generate PDF Dossier"],
      latency_ms: 1420,
    },
  },
  {
    id: "session-flood-assessment",
    title: "Flood Assessment",
    language: "en",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    category: "Yesterday",
    detail: {
      id: "session-flood-assessment",
      title: "Flood Assessment",
      language: "en",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
      messages: [
        {
          id: "m-flood-1",
          execution_id: null,
          role: "user",
          content: "Where are the inundated water bodies in this post-monsoon imagery?",
          created_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
        },
        {
          id: "m-flood-2",
          execution_id: "exec-flood-002",
          role: "assistant",
          content:
            "Surface water inundation is concentrated in the eastern floodplain. Approximately 28.6% of the surveyed zone exhibits water-like spectral characteristics with high NDWI values (>0.35).",
          created_at: new Date(Date.now() - 1000 * 60 * 59 * 26).toISOString(),
        },
      ],
    },
    result: {
      execution_id: "exec-flood-002",
      status: "completed",
      task: "grounding",
      model: "SatQuery Vision (GeoChat-7B)",
      model_version: "1.4.0",
      answer:
        "Surface water inundation is concentrated in the eastern floodplain. Approximately 28.6% of the surveyed zone exhibits water-like spectral characteristics with high NDWI values (>0.35).",
      evidence: [
        {
          type: "bounding_box",
          storage_key: "demo/single/water_grounding_bbox.png",
          coordinates: [85.12, 25.59, 85.24, 25.68],
          geo_geometry: null,
          label: "Inundation Extent",
          score: 0.96,
          area_m2: 3420000,
          area_percentage: 28.6,
        },
      ],
      confidence: {
        mode: "calibrated",
        overall_level: "high",
        model_confidence: 0.94,
        input_quality: "good",
        evidence_quality: "strong",
        modality_agreement: "not_applicable",
        notes: ["Validated against NIR band absorption pattern"],
      },
      data_provenance: {
        provider: "Sentinel-2 MSI",
        scene_id: "S2A_OPER_MSI_L2A_20240915",
        acquisition_date: "2024-09-15T04:45:10Z",
        sensor: "Optical Multispectral",
        aoi: null,
        crs: "EPSG:4326",
        resolution: 10,
        processing_applied: ["MNDWI Indexing", "Morphological Masking"],
        retrieved_at: "2026-02-15T12:00:00Z",
      },
      model_provenance: {
        model_id: "satquery-vision",
        version: "1.4.0",
        capability: "grounding",
        configuration: { task: "water_segmentation" },
        fallback_used: false,
        fallback_reason: null,
        demo_mode: false,
      },
      warnings: [],
      user_message: null,
      actions: ["Export GeoJSON"],
      latency_ms: 980,
    },
  },
  {
    id: "session-mumbai-sar",
    title: "Mumbai SAR Analysis",
    language: "en",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(),
    category: "Previous 7 Days",
    detail: {
      id: "session-mumbai-sar",
      title: "Mumbai SAR Analysis",
      language: "en",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(),
      messages: [
        {
          id: "m-sar-1",
          execution_id: null,
          role: "user",
          content: "Use both optical and SAR images to identify coastal built-up areas through persistent cloud cover.",
          created_at: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(),
        },
        {
          id: "m-sar-2",
          execution_id: "exec-sar-003",
          role: "assistant",
          content:
            "By fusing Sentinel-1 C-band SAR VV/VH double-bounce backscatter with clear cloud-gap optical imagery, port infrastructure and high-density settlements along the peninsula are verified with 92% cross-modal agreement.",
          created_at: new Date(Date.now() - 1000 * 60 * 58 * 80).toISOString(),
        },
      ],
    },
    result: {
      execution_id: "exec-sar-003",
      status: "completed",
      task: "optical_sar_analysis",
      model: "SatQuery Fusion (TerraMind)",
      model_version: "1.0.0",
      answer:
        "By fusing Sentinel-1 C-band SAR VV/VH double-bounce backscatter with clear cloud-gap optical imagery, port infrastructure and high-density settlements along the peninsula are verified with 92% cross-modal agreement.",
      evidence: [
        {
          type: "overlay",
          storage_key: "demo/fusion/optical_sar_fusion_overlay.png",
          coordinates: [72.81, 18.92, 72.89, 19.04],
          geo_geometry: null,
          label: "SAR Double-Bounce + Optical Co-registered Fusion",
          score: 0.92,
          area_m2: 8900000,
          area_percentage: 33.1,
        },
      ],
      confidence: {
        mode: "calibrated",
        overall_level: "high",
        model_confidence: 0.92,
        input_quality: "good",
        evidence_quality: "strong",
        modality_agreement: "agree",
        notes: [
          "SAR penetration through 74% overcast optical scene",
          "High corner-reflector response aligns with dense high-rise coordinates",
        ],
      },
      data_provenance: {
        provider: "Copernicus Sentinel-1 + Sentinel-2",
        scene_id: "S1A_IW_GRDH_1SDV_20241020 + S2B_MSIL2A_20241020",
        acquisition_date: "2024-10-20T01:12:00Z",
        sensor: "C-SAR (VV+VH) & Optical MSI",
        aoi: null,
        crs: "EPSG:4326",
        resolution: 10,
        processing_applied: ["Radiometric Calibration", "Lee Speckle Filtering", "Range-Doppler Terrain Correction"],
        retrieved_at: "2026-02-10T08:00:00Z",
      },
      model_provenance: {
        model_id: "satquery-fusion-terramind",
        version: "1.0.0",
        capability: "optical_sar_fusion",
        configuration: { cross_modal_attention: true },
        fallback_used: false,
        fallback_reason: null,
        demo_mode: false,
      },
      warnings: [],
      user_message: null,
      actions: ["Export PDF Dossier"],
      latency_ms: 2150,
    },
  },
  {
    id: "session-agri-review",
    title: "Agricultural Land Review",
    language: "en",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
    category: "Older",
    detail: {
      id: "session-agri-review",
      title: "Agricultural Land Review",
      language: "en",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
      messages: [
        {
          id: "m-agri-1",
          execution_id: null,
          role: "user",
          content: "What crop phenology changes occurred in this irrigation basin?",
          created_at: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
        },
        {
          id: "m-agri-2",
          execution_id: "exec-agri-004",
          role: "assistant",
          content:
            "NDVI time-series analysis shows active vegetative vigor in 64.2% of circular pivot irrigation plots. Fallow parcels show dry soil spectra with NDVI < 0.18.",
          created_at: new Date(Date.now() - 1000 * 60 * 59 * 200).toISOString(),
        },
      ],
    },
    result: {
      execution_id: "exec-agri-004",
      status: "completed",
      task: "vqa",
      model: "SatQuery Earth (Prithvi-EO-2.0)",
      model_version: "2.0.0",
      answer:
        "NDVI time-series analysis shows active vegetative vigor in 64.2% of circular pivot irrigation plots. Fallow parcels show dry soil spectra with NDVI < 0.18.",
      evidence: [
        {
          type: "original",
          storage_key: "demo/single/agricultural_false_color.png",
          coordinates: null,
          geo_geometry: null,
          label: "NIR/Red/Green False Color Composite",
          score: 0.88,
          area_m2: null,
          area_percentage: 64.2,
        },
      ],
      confidence: {
        mode: "calibrated",
        overall_level: "medium",
        model_confidence: 0.88,
        input_quality: "fair",
        evidence_quality: "moderate",
        modality_agreement: "not_applicable",
        notes: ["Minor haze detected in southwest quadrant"],
      },
      data_provenance: {
        provider: "Landsat-9 OLI-2",
        scene_id: "LC09_L2SP_145041_20240412",
        acquisition_date: "2024-04-12T05:15:30Z",
        sensor: "Multispectral OLI-2",
        aoi: null,
        crs: "EPSG:32643",
        resolution: 30,
        processing_applied: ["TOA Reflectance", "NDVI Transform"],
        retrieved_at: "2026-01-20T14:00:00Z",
      },
      model_provenance: {
        model_id: "satquery-prithvi-earth",
        version: "2.0.0",
        capability: "vqa",
        configuration: { bands: ["B04", "B03", "B02", "B08"] },
        fallback_used: false,
        fallback_reason: null,
        demo_mode: false,
      },
      warnings: [],
      user_message: null,
      actions: ["Export GeoJSON"],
      latency_ms: 1100,
    },
  },
];
