import type { Conversation, ExecutionResult, SessionDetail, SessionSummary } from "./types";
import { SATELLITE_IMAGES } from "./satellite-assets";

export interface MockSessionItem extends SessionSummary {
  updated_at: string;
  category: "Today" | "Yesterday" | "Previous 7 Days" | "Older";
  detail: SessionDetail;
  result: ExecutionResult;
}

export const MOCK_SESSIONS: MockSessionItem[] = [
  {
    id: "session-new",
    title: "New Satellite Query",
    language: "en",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: "Today",
    detail: {
      id: "session-new",
      title: "New Satellite Query",
      language: "en",
      created_at: new Date().toISOString(),
      messages: [],
    },
    result: {
      execution_id: "",
      status: "completed",
      task: "vqa",
      model: "SatQuery Vision (GeoChat-7B)",
      model_version: "1.4.0",
      answer: "",
      evidence: [],
      confidence: {
        mode: "calibrated",
        overall_level: "high",
        model_confidence: 0.95,
        input_quality: "good",
        evidence_quality: "strong",
        modality_agreement: "not_applicable",
        notes: [],
      },
      data_provenance: null,
      model_provenance: null,
      warnings: [],
      user_message: null,
      actions: [],
      latency_ms: 0,
    },
  },
  {
    id: "session-pune-growth",
    title: "Pune Urban Expansion",
    language: "en",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    category: "Today",
    detail: {
      id: "session-pune-growth",
      title: "Pune Urban Expansion",
      language: "en",


      created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      messages: [
        {
          id: "m-1",
          execution_id: null,
          role: "user",
          content: "What changed between these two Sentinel-2 images of Pune peri-urban region?",
          created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        },
        {
          id: "m-2",
          execution_id: "exec-pune-001",
          role: "assistant",
          content:
            "Built-up development increased significantly across the northern portion of the area of interest (+12.4 hectares). Agricultural parcels transitioned into construction staging and compacted impervious surfaces between January 2024 and December 2024.",
          created_at: new Date(Date.now() - 1000 * 60 * 58 * 2).toISOString(),
        },
      ],
    },
    result: {
      execution_id: "exec-pune-001",
      status: "completed",
      task: "change_vqa",
      model: "SatQuery Change (ChangeFormer)",
      model_version: "2.1.0-georef",
      answer:
        "Built-up development increased across the northern portion of the area of interest (+12.4 hectares). Spectral change masks indicate conversion from low-biomass fallow plots to high-reflectance commercial and transport infrastructure.",
      evidence: [
        {
          type: "before_after",
          storage_key: "demo/temporal/comparison_composite.png",
          coordinates: [73.8567, 18.5204, 73.9142, 18.5789],
          geo_geometry: {
            type: "Polygon",
            coordinates: [
              [
                [73.8567, 18.5204],
                [73.9142, 18.5204],
                [73.9142, 18.5789],
                [73.8567, 18.5789],
                [73.8567, 18.5204],
              ],
            ],
          },
          label: "Bi-Temporal Alignment (T1: 2024-01-12 | T2: 2024-12-18)",
          score: 0.94,
          area_m2: 124000,
          area_percentage: 14.2,
        },
        {
          type: "change_mask",
          storage_key: "demo/temporal/change_mask_overlay.png",
          coordinates: [73.871, 18.542, 73.902, 18.571],
          geo_geometry: null,
          label: "Built-up Expansion (Otsu + Morphological Filtering)",
          score: 0.91,
          area_m2: 124000,
          area_percentage: 14.2,
        },
      ],
      confidence: {
        mode: "calibrated",
        overall_level: "high",
        model_confidence: 0.89,
        input_quality: "good",
        evidence_quality: "strong",
        modality_agreement: "agree",
        notes: [
          "Co-registration RMSE < 0.32 pixels",
          "Zero cloud contamination in validated AOI",
          "Calculated using EPSG:32643 UTM Zone 43N projected coordinates",
        ],
      },
      data_provenance: {
        provider: "Copernicus Sentinel-2 L2A",
        scene_id: "S2B_MSIL2A_20241218T053219_R019",
        acquisition_date: "2024-12-18T05:32:19Z",
        sensor: "MSI Optical",
        aoi: { type: "BBox", bounds: [73.8567, 18.5204, 73.9142, 18.5789] },
        crs: "EPSG:32643",
        resolution: 10,
        processing_applied: ["Orthorectification", "Atmospheric Correction", "Bilinear Warp Co-registration"],
        retrieved_at: "2026-03-01T10:00:00Z",
      },
      model_provenance: {
        model_id: "satquery-change-former",
        version: "2.1.0",
        capability: "change_detection",
        configuration: { threshold: "otsu_adaptive", window_size: 512 },
        fallback_used: false,
        fallback_reason: null,
        demo_mode: false,
      },
      warnings: [],
      user_message: null,
      actions: ["Export GeoJSON", "Generate PDF Dossier"],
      latency_ms: 1420,
    },
  },
  {
    id: "session-flood-assessment",
    title: "Mumbai SAR Flood Assessment",
    language: "en",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    category: "Yesterday",
    detail: {
      id: "session-flood-assessment",
      title: "Mumbai SAR Flood Assessment",
      language: "en",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
      messages: [
        {
          id: "m-flood-1",
          execution_id: null,
          role: "user",
          content: "Where are the inundated water bodies in this post-monsoon imagery?",
          created_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
        },
        {
          id: "m-flood-2",
          execution_id: "exec-flood-002",
          role: "assistant",
          content:
            "Surface water inundation is concentrated in the eastern floodplain. Approximately 28.6% of the surveyed zone exhibits water-like spectral characteristics with high NDWI values (>0.35).",
          created_at: new Date(Date.now() - 1000 * 60 * 59 * 26).toISOString(),
        },
      ],
    },
    result: {
      execution_id: "exec-flood-002",
      status: "completed",
      task: "grounding",
      model: "SatQuery Vision (GeoChat-7B)",
      model_version: "1.4.0",
      answer:
        "Surface water inundation is concentrated in the eastern floodplain. Approximately 28.6% of the surveyed zone exhibits water-like spectral characteristics with high NDWI values (>0.35).",
      evidence: [
        {
          type: "bounding_box",
          storage_key: "demo/single/water_grounding_bbox.png",
          coordinates: [85.12, 25.59, 85.24, 25.68],
          geo_geometry: null,
          label: "Inundation Extent",
          score: 0.96,
          area_m2: 3420000,
          area_percentage: 28.6,
        },
      ],
      confidence: {
        mode: "calibrated",
        overall_level: "high",
        model_confidence: 0.94,
        input_quality: "good",
        evidence_quality: "strong",
        modality_agreement: "not_applicable",
        notes: ["Validated against NIR band absorption pattern"],
      },
      data_provenance: {
        provider: "Sentinel-2 MSI",
        scene_id: "S2A_OPER_MSI_L2A_20240915",
        acquisition_date: "2024-09-15T04:45:10Z",
        sensor: "Optical Multispectral",
        aoi: null,
        crs: "EPSG:4326",
        resolution: 10,
        processing_applied: ["MNDWI Indexing", "Morphological Masking"],
        retrieved_at: "2026-02-15T12:00:00Z",
      },
      model_provenance: {
        model_id: "satquery-vision",
        version: "1.4.0",
        capability: "grounding",
        configuration: { task: "water_segmentation" },
        fallback_used: false,
        fallback_reason: null,
        demo_mode: false,
      },
      warnings: [],
      user_message: null,
      actions: ["Export GeoJSON"],
      latency_ms: 980,
    },
  },
  {
    id: "session-mumbai-sar",
    title: "Gujarat Agricultural Shift",
    language: "en",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(),
    category: "Previous 7 Days",
    detail: {
      id: "session-mumbai-sar",
      title: "Gujarat Agricultural Shift",
      language: "en",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(),
      messages: [
        {
          id: "m-sar-1",
          execution_id: null,
          role: "user",
          content: "Use both optical and SAR images to identify coastal built-up areas through persistent cloud cover.",
          created_at: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(),
        },
        {
          id: "m-sar-2",
          execution_id: "exec-sar-003",
          role: "assistant",
          content:
            "By fusing Sentinel-1 C-band SAR VV/VH double-bounce backscatter with clear cloud-gap optical imagery, port infrastructure and high-density settlements along the peninsula are verified with 92% cross-modal agreement.",
          created_at: new Date(Date.now() - 1000 * 60 * 58 * 80).toISOString(),
        },
      ],
    },
    result: {
      execution_id: "exec-sar-003",
      status: "completed",
      task: "optical_sar_analysis",
      model: "SatQuery Fusion (TerraMind)",
      model_version: "1.0.0",
      answer:
        "By fusing Sentinel-1 C-band SAR VV/VH double-bounce backscatter with clear cloud-gap optical imagery, port infrastructure and high-density settlements along the peninsula are verified with 92% cross-modal agreement.",
      evidence: [
        {
          type: "overlay",
          storage_key: "demo/fusion/optical_sar_fusion_overlay.png",
          coordinates: [72.81, 18.92, 72.89, 19.04],
          geo_geometry: null,
          label: "SAR Double-Bounce + Optical Co-registered Fusion",
          score: 0.92,
          area_m2: 8900000,
          area_percentage: 33.1,
        },
      ],
      confidence: {
        mode: "calibrated",
        overall_level: "high",
        model_confidence: 0.92,
        input_quality: "good",
        evidence_quality: "strong",
        modality_agreement: "agree",
        notes: [
          "SAR penetration through 74% overcast optical scene",
          "High corner-reflector response aligns with dense high-rise coordinates",
        ],
      },
      data_provenance: {
        provider: "Copernicus Sentinel-1 + Sentinel-2",
        scene_id: "S1A_IW_GRDH_1SDV_20241020 + S2B_MSIL2A_20241020",
        acquisition_date: "2024-10-20T01:12:00Z",
        sensor: "C-SAR (VV+VH) & Optical MSI",
        aoi: null,
        crs: "EPSG:4326",
        resolution: 10,
        processing_applied: ["Radiometric Calibration", "Lee Speckle Filtering", "Range-Doppler Terrain Correction"],
        retrieved_at: "2026-02-10T08:00:00Z",
      },
      model_provenance: {
        model_id: "satquery-fusion-terramind",
        version: "1.0.0",
        capability: "optical_sar_fusion",
        configuration: { cross_modal_attention: true },
        fallback_used: false,
        fallback_reason: null,
        demo_mode: false,
      },
      warnings: [],
      user_message: null,
      actions: ["Export PDF Dossier"],
      latency_ms: 2150,
    },
  },
  {
    id: "session-agri-review",
    title: "Bangalore Lake Encroachment",
    language: "en",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
    category: "Older",
    detail: {
      id: "session-agri-review",
      title: "Bangalore Lake Encroachment",
      language: "en",

      created_at: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
      messages: [
        {
          id: "m-agri-1",
          execution_id: null,
          role: "user",
          content: "What crop phenology changes occurred in this irrigation basin?",
          created_at: new Date(Date.now() - 1000 * 60 * 60 * 200).toISOString(),
        },
        {
          id: "m-agri-2",
          execution_id: "exec-agri-004",
          role: "assistant",
          content:
            "NDVI time-series analysis shows active vegetative vigor in 64.2% of circular pivot irrigation plots. Fallow parcels show dry soil spectra with NDVI < 0.18.",
          created_at: new Date(Date.now() - 1000 * 60 * 59 * 200).toISOString(),
        },
      ],
    },
    result: {
      execution_id: "exec-agri-004",
      status: "completed",
      task: "vqa",
      model: "SatQuery Earth (Prithvi-EO-2.0)",
      model_version: "2.0.0",
      answer:
        "NDVI time-series analysis shows active vegetative vigor in 64.2% of circular pivot irrigation plots. Fallow parcels show dry soil spectra with NDVI < 0.18.",
      evidence: [
        {
          type: "original",
          storage_key: "demo/single/agricultural_false_color.png",
          coordinates: null,
          geo_geometry: null,
          label: "NIR/Red/Green False Color Composite",
          score: 0.88,
          area_m2: null,
          area_percentage: 64.2,
        },
      ],
      confidence: {
        mode: "calibrated",
        overall_level: "medium",
        model_confidence: 0.88,
        input_quality: "fair",
        evidence_quality: "moderate",
        modality_agreement: "not_applicable",
        notes: ["Minor haze detected in southwest quadrant"],
      },
      data_provenance: {
        provider: "Landsat-9 OLI-2",
        scene_id: "LC09_L2SP_145041_20240412",
        acquisition_date: "2024-04-12T05:15:30Z",
        sensor: "Multispectral OLI-2",
        aoi: null,
        crs: "EPSG:32643",
        resolution: 30,
        processing_applied: ["TOA Reflectance", "NDVI Transform"],
        retrieved_at: "2026-01-20T14:00:00Z",
      },
      model_provenance: {
        model_id: "satquery-prithvi-earth",
        version: "2.0.0",
        capability: "vqa",
        configuration: { bands: ["B04", "B03", "B02", "B08"] },
        fallback_used: false,
        fallback_reason: null,
        demo_mode: false,
      },
      warnings: [],
      user_message: null,
      actions: ["Export GeoJSON"],
      latency_ms: 1100,
    },
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: "chat-new",
    title: "New Satellite Query",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    temporary: false,
    category: "Today",
    messages: [],
  },
  {
    id: "chat-001",
    title: "Pune Urban Expansion",
    createdAt: "2026-08-30T10:14:00Z",
    updatedAt: "2026-08-30T10:18:22Z",
    temporary: false,
    category: "Today",
    activeTask: "Change Detection Model + GeoChat",
    aoiName: "Pune Peri-Urban Sector, Maharashtra",
    messages: [
      {
        id: "msg-001-u",
        role: "user",
        content: "What changed between these two Sentinel-2 acquisitions of northern Pune? Quantify the new built-up area and structural additions.",
        timestamp: "2026-08-30T10:14:00Z",
        attachments: [
          {
            id: "att-001",
            name: "sentinel2_pune_20240112_b432.tif",
            size: "14.2 MB",
            type: "image/geotiff",
            url: SATELLITE_IMAGES.puneBefore,
            sensor: "Sentinel-2",
            date: "2024-01-12",
            resolution: "10m",
            role: "baseline",
          },
          {
            id: "att-002",
            name: "sentinel2_pune_20250118_b432.tif",
            size: "14.6 MB",
            type: "image/geotiff",
            url: SATELLITE_IMAGES.puneAfter,
            sensor: "Sentinel-2",
            date: "2025-01-18",
            resolution: "10m",
            role: "comparison",
          },
        ],
      },
      {
        id: "msg-001-a",
        role: "assistant",
        content:
          "Built-up development increased significantly across the northern portion of the area of interest.\n\nBi-temporal spatial comparison between Sentinel-2 acquisitions (2024-01-12 vs 2025-01-18) reveals 12.4 hectares of newly constructed industrial facilities and residential foundations. The primary cluster is situated along the northern transit spur (UTM Zone 43N), transitioning former semi-arid agricultural plots into impermeable surfaces.",
        timestamp: "2026-08-30T10:18:22Z",
        analysisTrace: {
          task: "Bi-Temporal Optical Change Detection",
          sensor: "Sentinel-2 MSI (10m Resolution)",
          dateRange: "2024-01-12 → 2025-01-18",
          models: ["Change Detection Model", "GeoChat"],
          confidence: 0.87,
          confidenceTier: "High",
          outputType: "Segmented Change Mask + Sub-pixel Differential Vector Layer",
          executionSteps: [
            {
              name: "Sub-pixel Radiometric Coregistration",
              status: "completed",
              durationMs: 210,
              description: "Matched tie-points across both imagery timestamps with RMSE < 0.18 pixels.",
            },
            {
              name: "Deep Feature Differential Mapping",
              status: "completed",
              durationMs: 540,
              description: "Extracted persistent structural differences using Change Detection Model.",
            },
            {
              name: "Otsu Adaptive Thresholding & Morphology",
              status: "completed",
              durationMs: 180,
              description: "Isolated solid built-up expansion clusters from transient agricultural variations.",
            },
            {
              name: "Area Metric Integration (UTM EPSG:32643)",
              status: "completed",
              durationMs: 160,
              description: "Computed 12.4 ha net spatial transformation with ±0.3 ha statistical confidence interval.",
            },
          ],
        },
        evidence: {
          sourceImage: SATELLITE_IMAGES.puneBefore,
          highlightedImage: SATELLITE_IMAGES.puneAfter,
          changeMask: SATELLITE_IMAGES.puneChangeMask,
          aoi: {
            name: "Northern Pune Transit Corridor",
            coordinates: "18.5204° N, 73.8567° E",
            crs: "WGS84 / UTM Zone 43N",
            areaSqKm: 14.8,
          },
          metrics: [
            { label: "Detected Change", value: "+12.4 ha", change: "Quantified" },
            { label: "Coregistration Error", value: "0.18 px", change: "Sub-pixel" },
            { label: "Confidence Score", value: "87%", change: "High" },
            { label: "Baseline Coverage", value: "2024-01 → 2025-01", change: "372d" },
          ],
        },
        changeAnalysis: {
          beforeImage: SATELLITE_IMAGES.puneBefore,
          afterImage: SATELLITE_IMAGES.puneAfter,
          changeMaskImage: SATELLITE_IMAGES.puneChangeMask,
          beforeDate: "Jan 12, 2024",
          afterDate: "Jan 18, 2025",
          sensor: "Sentinel-2",
          areaHa: 12.4,
          changeType: "Vegetation & Barren → Impervious Built-up",
          summary: "12.4 ha of new industrial warehousing and logistics structures identified in northern AOI sector.",
          detectedClasses: [
            { name: "Industrial / Commercial Roofs", areaHa: 7.8, percentage: 63 },
            { name: "Paved Yards & Access Roads", areaHa: 3.2, percentage: 26 },
            { name: "Excavated Ground / Foundation", areaHa: 1.4, percentage: 11 },
          ],
        },
      },
    ],
  },
  {
    id: "chat-002",
    title: "Mumbai SAR Flood Assessment",
    createdAt: "2026-08-29T14:22:00Z",
    updatedAt: "2026-08-29T14:25:10Z",
    temporary: false,
    category: "Yesterday",
    activeTask: "Optical + SAR Multimodal Fusion",
    aoiName: "Mithi River Catchment, Mumbai",
    messages: [
      {
        id: "msg-002-u",
        role: "user",
        content: "Assess monsoon flooding in the Mithi catchment. Optical imagery has heavy cloud obscuration. Use Sentinel-1 SAR backscatter to map water accumulation.",
        timestamp: "2026-08-29T14:22:00Z",
        attachments: [
          {
            id: "att-003",
            name: "sentinel2_mumbai_cloudy.tif",
            size: "18.1 MB",
            type: "image/geotiff",
            url: SATELLITE_IMAGES.opticalCloudy,
            sensor: "Sentinel-2",
            date: "2026-08-28",
            resolution: "10m",
            role: "optical",
          },
          {
            id: "att-004",
            name: "sentinel1_grd_c_band_sar.tif",
            size: "22.4 MB",
            type: "image/geotiff",
            url: SATELLITE_IMAGES.sarRadar,
            sensor: "Sentinel-1 SAR",
            date: "2026-08-28",
            resolution: "10m (IW Mode)",
            role: "sar",
          },
        ],
      },
      {
        id: "msg-002-a",
        role: "assistant",
        content:
          "Multimodal fusion successfully penetrated 88.4% optical cloud cover using Sentinel-1 C-band SAR backscatter.\n\nSAR specular reflectance analysis indicates 410 hectares of severe inundation across low-lying sections of the Mithi River basin. Smooth open water surfaces exhibit characteristic low backscatter (-22.4 dB in VV polarization), clearly delineating standing flood water from urban high-backscatter structures.",
        timestamp: "2026-08-29T14:25:10Z",
        analysisTrace: {
          task: "Multimodal Optical + SAR Inundation Mapping",
          sensor: "Sentinel-1 IW SAR (C-Band) + Sentinel-2 Optical",
          dateRange: "2026-08-28",
          models: ["TerraMind", "Prithvi-EO", "GeoChat"],
          confidence: 0.92,
          confidenceTier: "High",
          outputType: "Fused SAR-Optical Watermask + Hydrological Inundation Layer",
          executionSteps: [
            {
              name: "Cloud Masking & Quality Assessment",
              status: "completed",
              durationMs: 120,
              description: "Identified 88.4% cloud occlusion in Sentinel-2 scene; automatically triggered SAR failover routing.",
            },
            {
              name: "SAR Radiometric Calibration & Terrain Correction",
              status: "completed",
              durationMs: 480,
              description: "Calibrated gamma0 backscatter coefficients with Copernicus 30m DEM.",
            },
            {
              name: "Speckle Filtering & Otsu Thresholding",
              status: "completed",
              durationMs: 340,
              description: "Applied refined Lee speckle filter (7x7 window) and segmented specular water reflections.",
            },
            {
              name: "TerraMind Multimodal Representation Fusion",
              status: "completed",
              durationMs: 710,
              description: "Fused SAR water boundary vectors with optical baseline elevation topography.",
            },
            {
              name: "Hydrological Flood Area Extraction",
              status: "completed",
              durationMs: 290,
              description: "Derived 410 ha flood polygon with 92% classification confidence.",
            },
          ],
        },
        multimodal: {
          opticalImage: SATELLITE_IMAGES.opticalCloudy,
          sarImage: SATELLITE_IMAGES.sarRadar,
          fusedImage: SATELLITE_IMAGES.fusedMultimodal,
          opticalSensor: "Sentinel-2 MSI (Optical)",
          sarSensor: "Sentinel-1 C-Band SAR (Radar)",
          opticalInsight: "88.4% Cloud Obscuration. Optical bands blocked by dense monsoon cloud cover.",
          sarInsight: "100% Cloud Penetration. Calibrated -22.4 dB backscatter isolates specular water.",
          fusedInsight: "Combined 410 ha inundation mask mapped directly against urban terrain infrastructure.",
        },
        evidence: {
          sourceImage: SATELLITE_IMAGES.sarRadar,
          highlightedImage: SATELLITE_IMAGES.fusedMultimodal,
          aoi: {
            name: "Mithi Catchment Inundation Zone",
            coordinates: "19.0760° N, 72.8777° E",
            crs: "WGS84 / UTM Zone 43N",
            areaSqKm: 16.2,
          },
          metrics: [
            { label: "Detected Inundation", value: "410 ha", change: "Critical" },
            { label: "Cloud Penetration", value: "100%", change: "SAR active" },
            { label: "Water Threshold", value: "-22.4 dB", change: "Specular" },
            { label: "Fused Confidence", value: "92%", change: "High" },
          ],
        },
      },
    ],
  },
  {
    id: "chat-003",
    title: "Gujarat Agricultural Shift",
    createdAt: "2026-08-25T09:10:00Z",
    updatedAt: "2026-08-25T09:12:30Z",
    temporary: false,
    category: "Previous 7 Days",
    activeTask: "Multispectral Crop Health",
    aoiName: "Saurashtra Agricultural Region, Gujarat",
    messages: [
      {
        id: "msg-003-u",
        role: "user",
        content: "Evaluate vegetation vigor and crop stress across this agricultural zone using Red-Edge and NIR reflectance indices.",
        timestamp: "2026-08-25T09:10:00Z",
      },
      {
        id: "msg-003-a",
        role: "assistant",
        content:
          "Multispectral NDVI and NDRE analysis demonstrates strong vegetative vigor across irrigated central zones (mean NDVI 0.68), while outer rainfed parcels indicate localized moisture stress.\n\nSpectral reflectance curve comparisons highlight elevated chlorophyll absorption in plots receiving drip irrigation, contrasting with early canopy senescence in peripheral fields.",
        timestamp: "2026-08-25T09:12:30Z",
        analysisTrace: {
          task: "Multispectral Crop Index Computation",
          sensor: "Sentinel-2 MSI (13 Bands)",
          dateRange: "2026-08-20",
          models: ["Prithvi-EO", "GeoChat"],
          confidence: 0.89,
          confidenceTier: "High",
          outputType: "Zonal Statistics & Crop Health Distribution",
          executionSteps: [
            {
              name: "Atmospheric Correction & BOA Calibration",
              status: "completed",
              durationMs: 150,
              description: "Calibrated Top-of-Atmosphere radiances to Bottom-of-Atmosphere surface reflectances.",
            },
            {
              name: "Band Ratio Matrix Calculation",
              status: "completed",
              durationMs: 280,
              description: "Derived NDVI ((B08-B04)/(B08+B04)) and NDRE ((B08-B05)/(B08+B05)) raster grids.",
            },
            {
              name: "Prithvi-EO Geospatial Embedding Extraction",
              status: "completed",
              durationMs: 510,
              description: "Classified canopy structure and phenology stage with foundation Earth-observation model.",
            },
            {
              name: "Zonal Boundary Statistical Aggregation",
              status: "completed",
              durationMs: 220,
              description: "Aggregated field-level distribution metrics across 340 distinct agricultural parcels.",
            },
          ],
        },
        evidence: {
          sourceImage: SATELLITE_IMAGES.puneBefore,
          aoi: {
            name: "Saurashtra Crop Sector",
            coordinates: "21.5222° N, 70.4579° E",
            crs: "WGS84 / UTM Zone 42N",
            areaSqKm: 8.5,
          },
          metrics: [
            { label: "Mean NDVI", value: "0.68", change: "+0.12 vs avg" },
            { label: "Canopy Chlorophyll", value: "High", change: "NDRE 0.42" },
            { label: "Active Cultivation", value: "84.2%", change: "Stable" },
          ],
        },
      },
    ],
  },
  {
    id: "chat-004",
    title: "Bangalore Lake Encroachment",
    createdAt: "2026-08-18T16:00:00Z",
    updatedAt: "2026-08-18T16:03:00Z",
    temporary: false,
    category: "Older",
    activeTask: "Waterbody Surface Boundary Tracking",
    aoiName: "Bellandur Catchment, Bangalore",
    messages: [
      {
        id: "msg-004-u",
        role: "user",
        content: "Track waterbody shrinkage and perimeter encroachment for Bellandur Lake over the past 36 months.",
        timestamp: "2026-08-18T16:00:00Z",
      },
      {
        id: "msg-004-a",
        role: "assistant",
        content:
          "Open water surface area decreased from 362 ha to 318 ha (-12.1%) over the 36-month monitoring window.\n\nBoundary vector tracking identifies 44 hectares of cumulative perimeter encroachment, primarily along the eastern and south-eastern buffer zones due to structural landfilling and macrophyte siltation.",
        timestamp: "2026-08-18T16:03:00Z",
        analysisTrace: {
          task: "Long-term Hydrological Shoreline Tracking",
          sensor: "Landsat-8/9 OLI + Sentinel-2 MSI",
          dateRange: "2023-08 to 2026-08 (36 Months)",
          models: ["Change Detection Model", "GeoChat"],
          confidence: 0.91,
          confidenceTier: "High",
          outputType: "Temporal Vector Boundary Diff + Hydro-Statistical Trend",
          executionSteps: [
            {
              name: "Historical Scene Ingestion & Cloud Sieve",
              status: "completed",
              durationMs: 320,
              description: "Queried STAC catalog for 18 cloud-free seasonal scenes across 3-year baseline.",
            },
            {
              name: "Modified NDWI Water Extraction",
              status: "completed",
              durationMs: 410,
              description: "Computed MNDWI ((Green-SWIR)/(Green+SWIR)) to cleanly separate water from urban edges.",
            },
            {
              name: "Perimeter Vector Polygon Differential",
              status: "completed",
              durationMs: 360,
              description: "Quantified 44 ha shrinkage and vector contraction across eastern buffer coordinates.",
            },
          ],
        },
      },
    ],
  },
];

